GET http://localhost:8080/todos
###
POST http://localhost:8080/todo/new
Content-Type: application/json

{
    "text": "Test after closing MongoDB apps"
}
###
DELETE http://localhost:8080/todo/delete/

###
PUT http://localhost:8080/todo/complete/63c2ef090b9fa9353b369ba6
